use_frameworks!

target 'CustomDatePicker_Example' do
  pod 'CustomDatePicker', :path => '../'

  target 'CustomDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
