use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'CustomDatePicker_Example' do
  pod 'CustomDatePicker', :path => '../'

  target 'CustomDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
